services:
  nextjs:
    build: .
    environment:
      - NODE_ENV=production
    expose:
      - "3000"  # Only expose the port to other services, not to the host
    networks:
      - app-network

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0
    ports:
      - "3000:4180"  # Map port 3000 on the host to port 4180 in the container
    environment:
      - OAUTH2_PROXY_PROVIDER=${OAUTH2_PROXY_PROVIDER}
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_REDIRECT_URL=${OAUTH2_PROXY_REDIRECT_URL}
      - OAUTH2_PROXY_UPSTREAMS=${OAUTH2_PROXY_UPSTREAMS}
      - OAUTH2_PROXY_EMAIL_DOMAINS=${OAUTH2_PROXY_EMAIL_DOMAINS}
      - OAUTH2_PROXY_COOKIE_SAMESITE=${OAUTH2_PROXY_COOKIE_SAMESITE}
      - OAUTH2_PROXY_COOKIE_REFRESH=${OAUTH2_PROXY_COOKIE_REFRESH}
    command:
      - --http-address=0.0.0.0:4180
    depends_on:
      - nextjs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
